Libreria/libreria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from core import views
from store.urls import store_patterns
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.home, name="home"),
    path('admin/', admin.site.urls),
    path('about/', views.about, name="about"),
    path('pricing/', views.pricing, name="pricing"),
    path('faq/', views.faq, name="faq"),
    path('blog-home/', views.bloghome, name="blog-home"),
    path('blog-post/', views.blogpost, name="blog-post"),
    path('portfolio-item/', views.portfolioitem, name="portfolio-item"),
    path('portfolio-overview/', views.portfoliooverview, name="portfolio-overview"),
    path('contact/', include('contact.urls')),
    path('store/', include(store_patterns)),
    path('accounts/', include('django.contrib.auth.urls')),
    path('page/', include('pages.urls')),
    # Aumentar la lista de posibles urls en la raiz de la aplicación
    path('accounts/', include('registration.urls')),
    # Social Auth
    path('social-auth/', include('social_django.urls', namespace="social")),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Libreria/pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.PageListView.as_view(), name="pages"),
    path('<int:page_id>/',views.page, name="page"),
    path('<int:pk>/<slug:page_slug>',views.PageDetailView.as_view(), name="page_detail"),
    path('create_page/',views.PageCreateView.as_view(), name="create_page"),
    path('update_page/<int:pk>',views.PageUpdateView.as_view(), name="update_page"),
    path('delete_page/<int:pk>',views.PageDeleteView.as_view(), name="delete_page"),
]

Libreria/core/models.py
from django.db import models

# Create your models here.

Libreria/pages/models.py
from django.db import models

# Create your models here.
class Page(models.Model):
    title = models.CharField(max_length=200, verbose_name="Título")
    content = models.TextField(verbose_name="Content")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")
    class Meta:
        verbose_name = "página"
        verbose_name_plural = "páginas"
        ordering = ['title']
    def __str__(self):
        return self.title

Libreria/core/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'core/home.html')

def about(request):
    return render(request, 'core/about.html')

def pricing(request):
    return render(request, 'core/pricing.html')

def faq(request):
    return render(request, 'core/faq.html')

def bloghome(request):
    return render(request, 'core/blog-home.html')

def blogpost(request):
    return render(request, 'core/blog-post.html')

def portfolioitem(request):
    return render(request, 'core/portfolio-item.html')

def portfoliooverview(request):
    return render(request, 'core/portfolio-overview.html')

# def store(request):
#     return render(request, 'core/store.html')

# def contact(request):
#     return render(request, 'core/contact.html')

Libreria/core/templates/core/about.html
{% extends 'core/base.html' %}
{% block content %}
{% load static%}
    <!-- Header-->
    <header class="py-5">
        <div class="container px-5">
            <div class="row justify-content-center">
                <div class="col-lg-8 col-xxl-6">
                    <div class="text-center my-5">
                        <h1 class="fw-bolder mb-3">Our mission is to make building websites easier for everyone.</h1>
                        <p class="lead fw-normal text-muted mb-4">Start Bootstrap was built on the idea that quality, functional website templates and themes should be available to everyone. Use our open source, free products, or support us by purchasing one of our premium products or services.</p>
                        <a class="btn btn-primary btn-lg" href="#scroll-target">Read our story</a>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- About section one-->
    <section class="py-5 bg-light" id="scroll-target">
        <div class="container px-5 my-5">
            <div class="row gx-5 align-items-center">
                <div class="col-lg-6"><img class="img-fluid rounded mb-5 mb-lg-0" src="https://dummyimage.com/600x400/343a40/6c757d" alt="..." /></div>
                <div class="col-lg-6">
                    <h2 class="fw-bolder">Our founding</h2>
                    <p class="lead fw-normal text-muted mb-0">Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto est, ut esse a labore aliquam beatae expedita. Blanditiis impedit numquam libero molestiae et fugit cupiditate, quibusdam expedita, maiores eaque quisquam.</p>
                </div>
            </div>
        </div>
    </section>
    <!-- About section two-->
    <section class="py-5">
        <div class="container px-5 my-5">
            <div class="row gx-5 align-items-center">
                <div class="col-lg-6 order-first order-lg-last"><img class="img-fluid rounded mb-5 mb-lg-0" src="https://dummyimage.com/600x400/343a40/6c757d" alt="..." /></div>
                <div class="col-lg-6">
                    <h2 class="fw-bolder">Growth &amp; beyond</h2>
                    <p class="lead fw-normal text-muted mb-0">Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto est, ut esse a labore aliquam beatae expedita. Blanditiis impedit numquam libero molestiae et fugit cupiditate, quibusdam expedita, maiores eaque quisquam.</p>
                </div>
            </div>
        </div>
    </section>
    <!-- Team members section-->
    <section class="py-5 bg-light">
        <div class="container px-5 my-5">
            <div class="text-center">
                <h2 class="fw-bolder">Our team</h2>
                <p class="lead fw-normal text-muted mb-5">Dedicated to quality and your success</p>
            </div>
            <div class="row gx-5 row-cols-1 row-cols-sm-2 row-cols-xl-4 justify-content-center">
                <div class="col mb-5 mb-5 mb-xl-0">
                    <div class="text-center">
                        <img class="img-fluid rounded-circle mb-4 px-4" src="https://dummyimage.com/150x150/ced4da/6c757d" alt="..." />
                        <h5 class="fw-bolder">Ibbie Eckart</h5>
                        <div class="fst-italic text-muted">Founder &amp; CEO</div>
                    </div>
                </div>
                <div class="col mb-5 mb-5 mb-xl-0">
                    <div class="text-center">
                        <img class="img-fluid rounded-circle mb-4 px-4" src="https://dummyimage.com/150x150/ced4da/6c757d" alt="..." />
                        <h5 class="fw-bolder">Arden Vasek</h5>
                        <div class="fst-italic text-muted">CFO</div>
                    </div>
                </div>
                <div class="col mb-5 mb-5 mb-sm-0">
                    <div class="text-center">
                        <img class="img-fluid rounded-circle mb-4 px-4" src="https://dummyimage.com/150x150/ced4da/6c757d" alt="..." />
                        <h5 class="fw-bolder">Toribio Nerthus</h5>
                        <div class="fst-italic text-muted">Operations Manager</div>
                    </div>
                </div>
                <div class="col mb-5">
                    <div class="text-center">
                        <img class="img-fluid rounded-circle mb-4 px-4" src="https://dummyimage.com/150x150/ced4da/6c757d" alt="..." />
                        <h5 class="fw-bolder">Malvina Cilla</h5>
                        <div class="fst-italic text-muted">CTO</div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

Libreria/core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Modern Business - Start Bootstrap Template</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'core/img/favicon.ico' %}" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'core/css/styles.css' %}" rel="stylesheet" />
</head>

<body class="d-flex flex-column h-100">
    <main class="flex-shrink-0">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container px-5">
                <a class="navbar-brand ml-4" href="{% url 'home' %}"><i class="bi bi-book"></i>  Validoteca</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation"><span
                        class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link" href="{% url 'home' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'about' %}">Nosotros</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'contact' %}">Contacto</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'libros:libros' %}">Tienda</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'pricing' %}">Precios</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'faq' %}">FAQ</a></li>
                        <li>
                            <a href="#" onclick="realizaPedido();" class="nav-link text-secondary">
                                <i class="fas fa-shopping-cart"> <span id="cart-badge"
                                        class="badge badge-danger">0</span> </i>
                            </a>
                        </li>
                        {% if request.user.is_staff %}
                        <li class="nav-item {% if request.path == '/pages/' %} active {% endif %}">
                            <a class="nav-link text-white" href="{% url 'pages' %}">Mis páginas</a>
                        </li>
                        {% endif %}
                        {% if not request.user.is_authenticated %}
                        <li class="nav-item">
                            <a type="button" class="btn btn-success me-2" href="{% url 'login' %}">Acceder <i
                                    class="bi bi-unlock-fill"></i></a>
                        </li>
                        <li class="nav-item">
                            <a type="button" class="btn btn-light" href="{% url 'signup' %}">¡Registrate! <i
                                    class="bi bi-person-plus-fill"></i></a>
                            <!-- <a class="nav-link" href="{% url 'faq' %}">FAQ</a> -->
                        </li>
                        <li class="nav-item">
                            <a type="button" class="btn btn-light text-primary ms-2" href="{% url 'social:begin' 'google-oauth2' %}"><i class="bi bi-google"></i></a>
                            <!-- <a class="nav-link" href="{% url 'faq' %}">FAQ</a> -->
                        </li>
                        {% else %}

                        <li class="nav-item">
                            <p class="nav-link text-white">¡Hola <b>{{request.user.username}}</b>!</p>
                        </li>

                        <li class="nav-item">
                            <a type="button" class="btn btn-danger" href="{% url 'logout' %}">Cerrar sesión <i
                                    class="bi bi-box-arrow-in-right"></i></a>
                        </li>
                        {% endif %}
                        <!-- <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="navbarDropdownBlog" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Blog</a>
                                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownBlog">
                                    <li><a class="dropdown-item" href="{% url 'blog-home' %}">Blog Home</a></li>
                                    <li><a class="dropdown-item" href="{% url 'blog-post' %}">Blog Post</a></li>
                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="navbarDropdownPortfolio" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Portfolio</a>
                                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownPortfolio">
                                    <li><a class="dropdown-item" href="{% url 'portfolio-overview' %}">Portfolio Overview</a></li>
                                    <li><a class="dropdown-item" href="{% url 'portfolio-item' %}">Portfolio Item</a></li>
                                </ul>
                            </li> -->
                    </ul>
                </div>
            </div>
        </nav>
        {% block content %}
        {% endblock %}
    </main>
    <form id="form_compra" action="{% url 'libros:detalle_compra' %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="datos_compra" id="datos_compra">
    </form>
    <!-- Footer-->
    <footer class="bg-dark py-4 mt-auto">
        <div class="container px-5">
            <div class="row align-items-center justify-content-between flex-column flex-sm-row">
                <div class="col-auto">
                    <div class="small m-0 text-white">Copyright &copy; Your Website 2022</div>
                </div>
                <div class="col-auto">

                    {% load pages_extras %}
                    {% get_page_list as page_list %}
                    {% for page in page_list %}
                    <a class="link-light small" href="{% url 'page' page.id %}">{{page.title}}</a>
                    {% if not forloop.last %}
                    <span class="text-white mx-1">&middot;</span>
                    {% endif %}
                    {% endfor %}
                    <!-- <a class="link-light small" href="#!">Terms</a>
                    <span class="text-white mx-1">&middot;</span>
                    <a class="link-light small" href="#!">Contact</a> -->
                </div>
            </div>
        </div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'core/js/scripts.js' %} "></script>

    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <!-- * *                               SB Forms JS                               * *-->
    <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    {% if request.path == '/contact/' %}
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    {% endif %}

    <!-- Contenido JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <script>
        if (localStorage.getItem('cart') == null) {
            // limpiar el localstorage
            localStorage.clear();
            var cart = {};
        }
        else {
            cart = JSON.parse(localStorage.getItem('cart'))
            show_badge_cart(); // mostrar el badge de carrito
        }

        function show_badge_cart() {
            totalItems = 0;
            if (localStorage.getItem('cart') != null) {
                cart = JSON.parse(localStorage.getItem('cart'));
                for (const x in cart) {
                    totalItems += parseInt(cart[x]);
                }
            }
            $('#cart-badge').text(totalItems.toString());
        }

        function realizaPedido() {
            // datos_pedido
            if (localStorage.getItem('cart') != null) {
                cart = JSON.parse(localStorage.getItem('cart'));
                valores_pedido = ""
                for (const x in cart) {
                    valores_pedido += x + "-" + cart[x] + "|";
                }
                $('#datos_compra').val(valores_pedido)
                $('#form_compra').submit()
            }

        }
    </script>


    {% block contentJS %} {% endblock %}
</body>

</html>

Libreria/core/templates/core/blog-home.html
{% extends 'core/base.html' %}
{% block content %}
{% load static%}
<!-- Page Content-->
<section class="py-5">
    <div class="container px-5">
        <h1 class="fw-bolder fs-5 mb-4">Company Blog</h1>
        <div class="card border-0 shadow rounded-3 overflow-hidden">
            <div class="card-body p-0">
                <div class="row gx-0">
                    <div class="col-lg-6 col-xl-5 py-lg-5">
                        <div class="p-4 p-md-5">
                            <div class="badge bg-primary bg-gradient rounded-pill mb-2">News</div>
                            <div class="h2 fw-bolder">Article heading goes here</div>
                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique delectus ab doloremque, qui doloribus ea officiis...</p>
                            <a class="stretched-link text-decoration-none" href="#!">
                                Read more
                                <i class="bi bi-arrow-right"></i>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-6 col-xl-7"><div class="bg-featured-blog" style="background-image: url('https://dummyimage.com/700x350/343a40/6c757d')"></div></div>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="py-5 bg-light">
    <div class="container px-5">
        <div class="row gx-5">
            <div class="col-xl-8">
                <h2 class="fw-bolder fs-5 mb-4">News</h2>
                <!-- News item-->
                <div class="mb-4">
                    <div class="small text-muted">May 12, 2022</div>
                    <a class="link-dark" href="#!"><h3>Start Bootstrap releases Bootstrap 5 updates for templates and themes</h3></a>
                </div>
                <!-- News item-->
                <div class="mb-5">
                    <div class="small text-muted">January, 2023</div>
                    <a class="link-dark" href="#!"><h3>Bootstrap 5 has officially landed</h3></a>
                </div>
                <!-- News item-->
                <div class="mb-5">
                    <div class="small text-muted">March 30, 2022</div>
                    <a class="link-dark" href="#!"><h3>This is another news article headline, but this one is a little bit longer</h3></a>
                </div>
                <div class="text-end mb-5 mb-xl-0">
                    <a class="text-decoration-none" href="#!">
                        More news
                        <i class="bi bi-arrow-right"></i>
                    </a>
                </div>
            </div>
            <div class="col-xl-4">
                <div class="card border-0 h-100">
                    <div class="card-body p-4">
                        <div class="d-flex h-100 align-items-center justify-content-center">
                            <div class="text-center">
                                <div class="h6 fw-bolder">Contact</div>
                                <p class="text-muted mb-4">
                                    For press inquiries, email us at
                                    <br />
                                    <a href="#!">press@domain.com</a>
                                </p>
                                <div class="h6 fw-bolder">Follow us</div>
                                <a class="fs-5 px-2 link-dark" href="#!"><i class="bi-twitter"></i></a>
                                <a class="fs-5 px-2 link-dark" href="#!"><i class="bi-facebook"></i></a>
                                <a class="fs-5 px-2 link-dark" href="#!"><i class="bi-linkedin"></i></a>
                                <a class="fs-5 px-2 link-dark" href="#!"><i class="bi-youtube"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Blog preview section-->
<section class="py-5">
    <div class="container px-5">
        <h2 class="fw-bolder fs-5 mb-4">Featured Stories</h2>
        <div class="row gx-5">
            <div class="col-lg-4 mb-5">
                <div class="card h-100 shadow border-0">
                    <img class="card-img-top" src="https://dummyimage.com/600x350/ced4da/6c757d" alt="..." />
                    <div class="card-body p-4">
                        <div class="badge bg-primary bg-gradient rounded-pill mb-2">News</div>
                        <a class="text-decoration-none link-dark stretched-link" href="#!"><div class="h5 card-title mb-3">Blog post title</div></a>
                        <p class="card-text mb-0">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    </div>
                    <div class="card-footer p-4 pt-0 bg-transparent border-top-0">
                        <div class="d-flex align-items-end justify-content-between">
                            <div class="d-flex align-items-center">
                                <img class="rounded-circle me-3" src="https://dummyimage.com/40x40/ced4da/6c757d" alt="..." />
                                <div class="small">
                                    <div class="fw-bold">Kelly Rowan</div>
                                    <div class="text-muted">March 12, 2022 &middot; 6 min read</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 mb-5">
                <div class="card h-100 shadow border-0">
                    <img class="card-img-top" src="https://dummyimage.com/600x350/adb5bd/495057" alt="..." />
                    <div class="card-body p-4">
                        <div class="badge bg-primary bg-gradient rounded-pill mb-2">Media</div>
                        <a class="text-decoration-none link-dark stretched-link" href="#!"><div class="h5 card-title mb-3">Another blog post title</div></a>
                        <p class="card-text mb-0">This text is a bit longer to illustrate the adaptive height of each card. Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    </div>
                    <div class="card-footer p-4 pt-0 bg-transparent border-top-0">
                        <div class="d-flex align-items-end justify-content-between">
                            <div class="d-flex align-items-center">
                                <img class="rounded-circle me-3" src="https://dummyimage.com/40x40/ced4da/6c757d" alt="..." />
                                <div class="small">
                                    <div class="fw-bold">Josiah Barclay</div>
                                    <div class="text-muted">March 23, 2022 &middot; 4 min read</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 mb-5">
                <div class="card h-100 shadow border-0">
                    <img class="card-img-top" src="https://dummyimage.com/600x350/6c757d/343a40" alt="..." />
                    <div class="card-body p-4">
                        <div class="badge bg-primary bg-gradient rounded-pill mb-2">News</div>
                        <a class="text-decoration-none link-dark stretched-link" href="#!"><div class="h5 card-title mb-3">The last blog post title is a little bit longer than the others</div></a>
                        <p class="card-text mb-0">Some more quick example text to build on the card title and make up the bulk of the card's content.</p>
                    </div>
                    <div class="card-footer p-4 pt-0 bg-transparent border-top-0">
                        <div class="d-flex align-items-end justify-content-between">
                            <div class="d-flex align-items-center">
                                <img class="rounded-circle me-3" src="https://dummyimage.com/40x40/ced4da/6c757d" alt="..." />
                                <div class="small">
                                    <div class="fw-bold">Evelyn Martinez</div>
                                    <div class="text-muted">April 2, 2022 &middot; 10 min read</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="text-end mb-5 mb-xl-0">
            <a class="text-decoration-none" href="#!">
                More stories
                <i class="bi bi-arrow-right"></i>
            </a>
        </div>
    </div>
</section>
{% endblock %}

Libreria/core/templates/core/portfolio-item.html
{% extends 'core/base.html' %}
{% block content %}
{% load static%}
<!-- Page Content-->
<section class="py-5">
    <div class="container px-5 my-5">
        <div class="row gx-5 justify-content-center">
            <div class="col-lg-6">
                <div class="text-center mb-5">
                    <h1 class="fw-bolder">Project Title</h1>
                    <p class="lead fw-normal text-muted mb-0">Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab similique, ducimus ut alias sit accusamus illum, asperiores deserunt dolorum quaerat qui! Ab, quisquam explicabo magni dolores unde beatae quam a.</p>
                </div>
            </div>
        </div>
        <div class="row gx-5">
            <div class="col-12"><img class="img-fluid rounded-3 mb-5" src="https://dummyimage.com/1300x700/343a40/6c757d" alt="..." /></div>
            <div class="col-lg-6"><img class="img-fluid rounded-3 mb-5" src="https://dummyimage.com/600x400/343a40/6c757d" alt="..." /></div>
            <div class="col-lg-6"><img class="img-fluid rounded-3 mb-5" src="https://dummyimage.com/600x400/343a40/6c757d" alt="..." /></div>
        </div>
        <div class="row gx-5 justify-content-center">
            <div class="col-lg-6">
                <div class="text-center mb-5">
                    <p class="lead fw-normal text-muted">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Totam deserunt architecto enim eos accusantium fugit recusandae illo iste dignissimos possimus facere ducimus odit voluptatibus exercitationem, ex laudantium illum voluptatum corporis.</p>
                    <a class="text-decoration-none" href="#!">
                        View project
                        <i class="bi-arrow-right"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

Libreria/core/templates/core/portfolio-overview.html
{% extends 'core/base.html' %}
{% block content %}
{% load static%}
<!-- Page Content-->
<section class="py-5">
    <div class="container px-5 my-5">
        <div class="text-center mb-5">
            <h1 class="fw-bolder">Our Work</h1>
            <p class="lead fw-normal text-muted mb-0">Company portfolio</p>
        </div>
        <div class="row gx-5">
            <div class="col-lg-6">
                <div class="position-relative mb-5">
                    <img class="img-fluid rounded-3 mb-3" src="https://dummyimage.com/600x400/343a40/6c757d" alt="..." />
                    <a class="h3 fw-bolder text-decoration-none link-dark stretched-link" href="#!">Project name</a>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="position-relative mb-5">
                    <img class="img-fluid rounded-3 mb-3" src="https://dummyimage.com/600x400/343a40/6c757d" alt="..." />
                    <a class="h3 fw-bolder text-decoration-none link-dark stretched-link" href="#!">Project name</a>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="position-relative mb-5 mb-lg-0">
                    <img class="img-fluid rounded-3 mb-3" src="https://dummyimage.com/600x400/343a40/6c757d" alt="..." />
                    <a class="h3 fw-bolder text-decoration-none link-dark stretched-link" href="#!">Project name</a>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="position-relative">
                    <img class="img-fluid rounded-3 mb-3" src="https://dummyimage.com/600x400/343a40/6c757d" alt="..." />
                    <a class="h3 fw-bolder text-decoration-none link-dark stretched-link" href="#!">Project name</a>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="py-5 bg-light">
    <div class="container px-5 my-5">
        <h2 class="display-4 fw-bolder mb-4">Let's build something together</h2>
        <a class="btn btn-lg btn-primary" href="#!">Contact us</a>
    </div>
</section>
{% endblock %}